### ISSUE TITLE
Does this work with reverse proxy?

### ISSUE THREAD

**Issue by makailol** [taoyuanyuan/ngx_http_trim_filter_module#2]
Hi,

I would like to know few things about this module. I want to use this module in Nginx reverse proxy configuration.

1) Does this work with reverse proxy Nginx? i.e. Can it trim the upstream response ?
2) If it works with upstream response, does it buffer the full response from upstream server or can it process with upstream  chunk without break?
3) If upstream response is "gzip", is it possible to gunzip first and run this trim module on that?

Thanks,

**Comment by taoyuanyuan** [comment]
https://github.com/alibaba/tengine/issues/368
